language: node_js
dist: trusty
node_js:
- node
branches:
  only:
  - master
cache:
  yarn: true
  directories:
  - ".npm"
install:
- yarn install --frozen-lockfile
script:
- yarn lint
- yarn build
notifications:
  slack:
    secure: PVbDhz02jcgDceQwRMspvG8zCOflbRhOmnms2OXJs7MuqAMGE/fnTQTE9nVN5ibnCKUJ219xZSP5+BODDQ0rb1qGMEnm8jvMwO4IUFvcPMcV0TPimcex+t2P8+BeTrRzJ3Rdb0fxq55uUITHuQsqRHZC/Ey0ZTp66oJhTbpbMnCyi9h7IIdvpeULVfIxN69t+kH3l3pnULiMuh73LcxMMJ2CdwP6LLBeyLflQ3PM5C06joDrILFMrWHOW9hN53TVsL+GisofGE7mXQl2hHINmvcdpbUfYSqFbv3IzvMXZjld/dzeVZa2WNtxFz1RSj++TKTp2mu/zBtLCQU6S/LvdEA9TDdwOC5K6lrk7ZnQwP5VgylZ67fh/+ocwfZDwL2qQ50tppYwgRaFsd0fD/hrzcYpZj6el9t/wCN/to+N4WcoIAOPPK4JnpjwEro1XE7c9naamGYKMTCRMFKuXV8gBSkNAbXfSxm5iRZn0arcQovP9pSKq/f8Lf/TwGV+GH5EXCGKuF0hMegj+4FC0JERhWHrOZ6dtqGCH4RL3pzW5AORgBokj4QL3uELarOwufDkIR3EuLX/uXoz+m+i5cfR7igM2xwu8LjefnCkMu4eYPAmmxlqF9oJCJAtKyshHAbrdcyadbqrdrFTQ5AvejcGqDLm28eUGHAt9Zv8fltrSwM=
